### ISSUE TITLE
Error in form processing for some shops

### ISSUE THREAD

**Issue by beberlei** [tideways/shopware6-benchmarking#52]
```
Update register.json fixture data
Update listings and products from sitemap.xml
Running benchmark for 5m...
Traceback (most recent call last):
File "/usr/local/bin/locust", line 8, in <module>
sys.exit(main())
File "/usr/local/lib/python3.8/dist-packages/locust/main.py", line 125, in main
docstring, user_classes, shape_class = load_locustfile(locustfile)
File "/usr/local/lib/python3.8/dist-packages/locust/main.py", line 82, in load_locustfile
imported = source.load_module()
File "<frozen importlib._bootstrap_external>", line 522, in _check_name_wrapper
File "<frozen importlib._bootstrap_external>", line 1027, in load_module
File "<frozen importlib._bootstrap_external>", line 852, in load_module
File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
File "<frozen importlib._bootstrap>", line 702, in _load
File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 848, in exec_module
File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
File "/var/www/share/swbench/locustfile.py", line 31, in <module>
from locusthelpers.shopware_user import ShopwareUser
File "/var/www/share/swbench/locusthelpers/shopware_user.py", line 36, in <module>
from locusthelpers.authentication import Authentication
File "/var/www/share/swbench/locusthelpers/authentication.py", line 34, in <module>
from locusthelpers.form import getFormFieldOptionValues
File "/var/www/share/swbench/locusthelpers/form.py", line 42, in <module>
def getFormFieldOptionValues(response: Response, formAction: str, fieldName: str, filterEmpty=False) -> list[str]:
TypeError: 'type' object is not subscriptable
Complete after 1 seconds.
```

**Comment by beberlei** [comment]
@hco i could not reproduce this for https://sw6benchmark.c-397.maxcluster.net/account with this config: 

```json
{
    "scenario": {
        "title": "Benchmarking https:\/\/sw6benchmark.c-397.maxcluster.net\/",
        "duration": "60m",
        "host": "https:\/\/sw6benchmark.c-397.maxcluster.net\/",
        "description": "",
        "concurrentThreads": 10,
        "userSpawnRate": 1,
        "browsingGuestRatio": 50,
        "browsingAccountsNewRatio": 50,
        "checkoutGuestRatio": 50,
        "checkoutAccountsNewRatio": 50,
        "conversionRatio": 5,
        "cartAbandonmentRatio": 5,
        "filtererMinFilters": 3,
        "filtererMaxFilters": 5,
        "filtererVisitProductRatio": 10,
        "maxPaginationSurfing": 3
    },
    "shopware": {
        "version": "",
        "phpVersion": "",
        "serverHardware": ""
    },
    "tideways": {
        "apiToken": "",
        "project": "",
        "apiKey": "",
        "environment": "production",
        "traceSampleRate": 0
    }
}
```

The crash looks to be one that happens while compiling the code though, maybe a wrong python version? I'll ask the cusotmer.

**Comment by beberlei** [comment]
@hco vustomer has python 3.8.10, i have 3.9

**Comment by hco** [comment]
I just started to dig into this, and my first thought was:
Have you checked with the customer if the Docker-based setup would be an option for them?

**Comment by hco** [comment]
Some of the type syntax I used was not compatible with python 3.8. I **think** found a way to make it work in both versions.

I would suggest that we add a minimum python version requirement.
Looking at https://www.python.org/downloads/, I think I'd go for 3.9 o 3.10, but I'm also open to 3.8.
Locust has a minimum requirement of 3.6, but one of the plugins seems to break with 3.7 or below.

Random thought: Should we maybe setup some kind of CI/CD for different python versions? 🤔
